name: Deploy

on: 
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy do Datalake
    runs-on: ubuntu-lastest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-ptyhon@v2
      with: 
        python-version: 3.9

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ""
        aws-secret-access-key: ""
        aws-region: us-east-2

    - name: IaC Apply
      env: 
        COMMAND_IAC: terraform
      run:
        cd infrastructure
        $COMMAND_IAC init
        $COMMAND_IAC validate
        $COMMAND_IAC plan
        $COMMAND_IAC apply --auto-approve